version: "3.9"

services:

    database:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        networks:
            - app-virtual-network
        

    backend:
        build: ./backend
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - database
        networks:
            - app-virtual-network
        command: python manage.py runserver 0.0.0.0:8000
        
    frontend:
        build: 
            context: ./frontend
        ports:
           - 3000:3000
        env_file:
            - ./.env
        networks:
            - app-virtual-network
        command: node ./scripts/start.js

volumes:
    postgres_data:

networks:
    app-virtual-network: